# Generated by Django 5.2.17 on 2026-08-25 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='Veiculo.marca')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='Renavam')),
                ('capacidade', models.PositiveIntegerField(help_text='Deve estar entre 2 e 5 ocupantes.', validators=[django.core.validators.MinValueValidator(2, message='A capacidade mínima é de 2 pessoas.'), django.core.validators.MaxValueValidator(5, message='A capacidade máxima é de 5 pessoas.')])),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='Veiculo.modelo')),
            ],
            options={
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
